### ISSUE TITLE
Regex for filtering parameter names that contain a dot

### ISSUE THREAD

**Issue by shaoner** [jsdoc2md/ddata#2]
Hi,

Using an example will be simpler to explain but in method signature, when a parameter name contains a "." and a suffix which is not in [a-zA-Z0-9_], it's not filtered the same way: https://github.com/jsdoc2md/ddata/blob/master/lib/ddata.js#L595. I'm having this issue with jsdoc2md, for example:

```javascript
/**
* @param {Object} [options]
* @param {boolean} [options.foo]
* @param {string} [options.$bar]
*/
```

This results into "[options], [options.$bar]" instead of "[options]".

Not entirely sure about what ES5 says about valid identifier names, but "$" is supposed to be valid.
Taking all cases into account can be quite complicated, but at least this should work for US ascii even if incomplete:

```javascript
!/[$A-Z_][0-9A-Z_$]*\.[$A-Z_][0-9A-Z_$]*/i.test(param.name);
```
or simply by filtering parameters that contain a ".":

```javascript
!/\./.test(param.name);
```

**Comment by 75lb** [comment]
Yes, $ and _ are valid.. Will look at this asap, thanks for the report

**Comment by 75lb** [comment]
i apologise for the delay! this issue is fixed in the latest version of ddata (and jsdoc2md).
